default: true
header-increment: false
header-style:
  style: atx
ul-style:
  style: dash
code-block-style:
  style: fenced
code-fence-style:
  style: backtick
emphasis-style:
  style: underscore
strong-style:
  style: asterisk
