default: true
header-increment: false
blanks-around-headers: 0
header-style:
  style: atx
ul-style:
  style: dash
code-block-style:
  style: fenced
code-fence-style:
  style: backtick
emphasis-style:
  style: underscore
strong-style:
  style: asterisk
line-length:
  line_length: 250
  code_blocks: false
  tables: false
  headings: false
