name: Markdown Lint

on: [pull_request]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23.1
        with:
          files: |
            *.md
          files-ignore: |
            README.md
            .github/*
            LICENSE.md

      - name: Run Linter
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npm install -g markdownlint-cli
          markdownlint -c .github/linter/.markdown-lint.yml ${{ steps.changed-files.outputs.all_changed_files }}
