name: Markdown Lint

on: [pull_request]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - id: changed-files
        name: Get changed files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323
        with:
          files: |
            **/*.md
          files-ignore: |
            README.md
            .github/*
            LICENSE.md

      - name: Run Linter
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npm install -g markdownlint-cli
          markdownlint -c .github/linters/.markdown-lint.yml ${{ steps.changed-files.outputs.all_changed_files }}
