name: Markdown Lint

on: [pull_request]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
        
      - name: Get Changed Files
        id: linter-files
        run: |
          CHANGED_FILES=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD ${{ github.head_ref }}))
          echo "::set-output name=files::$(echo -e $CHANGED_FILES | grep -Po "^(.*(?<=md))$" | tr '\n' ' ')"

      - name: Run Linter
        run: markdownlint -c .github/linter/.markdown-lint.yml ${{ steps.run_tests.outputs.files }}
